spring:
  application:
    name: ResourceService
server:
  port: ${PORT:0}
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 1
    metadataMap:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}          
ribbon:
  eureka:
    enabled: true
security:
  oauth2:
    resource:
      userInfoUri: http://localhost:9000/authorize/user

logging.level.org.springframework.cloud.sleuth: DEBUG
logging.level.org.springframework.web.servlet.DispatcherServlet: DEBUG