spring:
  application:
    name: zipkin-service
server:
  port: 9411
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 1
    metadataMap:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}          
ribbon:
  eureka:
    enabled: true

logging.level.org.springframework.cloud.sleuth: DEBUG
logging.level.org.springframework.web.servlet.DispatcherServlet: DEBUG