spring:
  application:
    name: OrderService
server:
  port: 7161
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
          
ribbon:
  eureka:
    enabled: true